"""final

Revision ID: 3880d1a2418a
Revises: fff7e508e1f7
Create Date: 2024-02-05 10:05:00.404533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3880d1a2418a'
down_revision = 'fff7e508e1f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_index(batch_op.f('ix_truck_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_truck_email'))
        batch_op.drop_column('email')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
