"""reverted to old

Revision ID: bebd31a26702
Revises: 2976d6b91dde
Create Date: 2024-02-03 15:23:07.320609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebd31a26702'
down_revision = '2976d6b91dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.drop_index('ix_truck_driver_name')

    op.drop_table('truck')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.drop_column('location')
        batch_op.drop_column('registration_date')
        batch_op.drop_column('phone')
        batch_op.drop_column('scheduled_pickup_alerts')
        batch_op.drop_column('proximity_alerts')
        batch_op.drop_column('usage_history')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('notification_preferences')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_preferences', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('subscription_status', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('usage_history', sa.VARCHAR(length=1000), nullable=False))
        batch_op.add_column(sa.Column('proximity_alerts', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('scheduled_pickup_alerts', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('registration_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    op.create_table('truck',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('driver_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('license_plate', sa.VARCHAR(length=20), nullable=False),
    sa.Column('schedule', sa.VARCHAR(length=20), nullable=False),
    sa.Column('current_location', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('capacity', sa.INTEGER(), nullable=False),
    sa.Column('last_pickup_time', sa.DATETIME(), nullable=False),
    sa.Column('next_pickup_date', sa.DATETIME(), nullable=False),
    sa.Column('waste_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('route', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.create_index('ix_truck_driver_name', ['driver_name'], unique=False)

    # ### end Alembic commands ###
