"""final_4

Revision ID: e75667949f3f
Revises: f4e24ca29a59
Create Date: 2024-02-05 11:22:52.902587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75667949f3f'
down_revision = 'f4e24ca29a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.drop_column('last_pickup_time')
        batch_op.drop_column('status')
        batch_op.drop_column('district')
        batch_op.drop_column('next_pickup_date')
        batch_op.drop_column('current_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_location', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('next_pickup_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('district', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('last_pickup_time', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
