"""final_3

Revision ID: f4e24ca29a59
Revises: 3880d1a2418a
Create Date: 2024-02-05 11:22:14.137179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e24ca29a59'
down_revision = '3880d1a2418a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.drop_column('schedule')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
