"""switching to new db

Revision ID: fff7e508e1f7
Revises: bebd31a26702
Create Date: 2024-02-03 17:26:56.678985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff7e508e1f7'
down_revision = 'bebd31a26702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('truck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=64), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('schedule', sa.String(length=20), nullable=False),
    sa.Column('current_location', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_pickup_time', sa.DateTime(), nullable=False),
    sa.Column('next_pickup_date', sa.DateTime(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_truck_driver_name'), ['driver_name'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('scheduled_pickup_alerts', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('proximity_alerts', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('registration_date', sa.DateTime(), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DATETIME(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.drop_column('registration_date')
        batch_op.drop_column('phone')
        batch_op.drop_column('proximity_alerts')
        batch_op.drop_column('scheduled_pickup_alerts')
        batch_op.drop_column('location')

    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_truck_driver_name'))

    op.drop_table('truck')
    # ### end Alembic commands ###
